language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
  - EMBER_TRY_SCENARIO=ember-1.10
  - EMBER_TRY_SCENARIO=ember-1.11
  - EMBER_TRY_SCENARIO=ember-1.12
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-beta
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-canary
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test
notifications:
  slack:
    secure: CFrL/oc/ykd0EYq+ALt3m8OesWHttVV6bP1ljgY8PrPHJRUcFUH4qil3fgdoziWlWfsn8Lub6QaXmJ+bAecHFgYR4ckV5bIW+ek+v06URG4hrtomsEwG1Vm28zlWrhdSgBCRDQp1xTTHzv+amlygPCf7J6rwE0U2vzkPL6lPQZZ2kd2wgJvOamdqgZAbA1oxlQD+KLwt4/EAdJwVzJ2YqCYNnwiMEkZOOqYRwAwKQa2pcxY+FE9moBkGdVJdh8T0Gg+4fP4+wa/tRnDIm4QTxK9Om0mxNU4odJUSV5iKbw3DGz8x1s0bQKIdGww5DRQA+fSl0yZt+UVGOFvvG/M9mPEWwn/SYFSkKAiNs0LDvmJTZXjYsIkpvHYUYatBWEWsNBjwZlf4E1rrIWDD/laE1jR0S7G+mUQy0hVB4e+AgLX9XclgQeFmNKfDn4jww8sYdera7zP+/04q3adfeGiG+lUwd7OR+lQu3ya6N+28W4t0HfpQVRli3bsbDt3s+35LUPRfYVTi1IQG11NzP0ApsASCXk37nqTgbd9IgVUbUWI6jCvVcJa/3U/10d4GvB/Qiyjbw3X5589wHfJlQ1E721XEUOpa1Fih1gr1vjJPXgqPO5vGHvtLc47FC2zcg3tgQlNOktI3QAJJE3lNjXI0XehhDnseBqwm7+vm4JFItiU=
